@startuml

title __PORT's Class Diagram__\n

  namespace fourcats {
    namespace port {
      interface fourcats.port.AddBalSuggestionInputPort {
          {abstract} + addSuggestion()
          {abstract} + addSuggestionByIdType()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.AddBalSuggestionOutputPort {
          {abstract} + showAddedSuggestion()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.CreateCustomTypeInputPort {
          {abstract} + createType()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.CreateCustomTypeOutputPort {
          {abstract} + showCustomTypeCreationStatus()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.DeclineBalSuggestionInputPort {
          {abstract} + declineSuggestion()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.DeclineBalSuggestionOutputPort {
          {abstract} + showDeclinedSuggestion()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.GenerateBalInputPort {
          {abstract} + generateBAL()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.GenerateBalOutputPort {
          {abstract} + showGenerationStatus()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.GenerateBalSuggestionsInputPort {
          {abstract} + generateSuggestions()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.GenerateBalSuggestionsOutputPort {
          {abstract} + showErrorFileLoad()
          {abstract} + showSuggestionsForScenario()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.LoadBdlInputPort {
          {abstract} + loadingBdl()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.LoadBdlOutputPort {
          {abstract} + showBDLOutput()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.ModifyBalSuggestionInputPort {
          {abstract} + addObject()
          {abstract} + modifyActionName()
          {abstract} + modifyActionType()
          {abstract} + modifyActionTypeById()
          {abstract} + modifyObjectName()
          {abstract} + modifyObjectType()
          {abstract} + modifyObjectTypeById()
          {abstract} + removeObject()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.ModifyBalSuggestionOutputPort {
          {abstract} + showAddedObject()
          {abstract} + showModifiedActionName()
          {abstract} + showModifiedActionType()
          {abstract} + showModifiedObjectName()
          {abstract} + showModifiedObjectType()
          {abstract} + showRemovedObject()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.RemoveBdlInputPort {
          {abstract} + removeLoadedBdl()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.RemoveBdlOutputPort {
          {abstract} + showRemoveBdlStatus()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.ShowTypesInputPort {
          {abstract} + showTypes()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.ShowTypesOutputPort {
          {abstract} + showTypes()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
