@startuml

title __PORT's Class Diagram__\n

  namespace fourcats {
    namespace port {
      interface fourcats.port.CreateCustomTypeInputPort {
          {abstract} + createType()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.CreateCustomTypeOutputPort {
          {abstract} + showCustomTypeCreationStatus()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.DeclineBALSuggestionInputPort {
          {abstract} + declineSuggestion()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.DeclineBALSuggestionOutputPort {
          {abstract} + showDeclinedSuggestion()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.GenerateBALInputPort {
          {abstract} + generateBAL()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.GenerateBALOutputPort {
          {abstract} + showGenerationStatus()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.GenerateBALSuggestionsInputPort {
          {abstract} + generateSuggestions()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.GenerateBALSuggestionsOutputPort {
          {abstract} + showErrorFileLoad()
          {abstract} + showSuggestionsForScenario()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.ModifyBALSuggestionInputPort {
          {abstract} + addObject()
          {abstract} + modifyActionName()
          {abstract} + modifyActionType()
          {abstract} + modifyActionTypeById()
          {abstract} + modifyObjectName()
          {abstract} + modifyObjectType()
          {abstract} + modifyObjectTypeById()
          {abstract} + removeObject()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.ModifyBALSuggestionOutputPort {
          {abstract} + showAddedObject()
          {abstract} + showModifiedActionName()
          {abstract} + showModifiedActionType()
          {abstract} + showModifiedObjectName()
          {abstract} + showModifiedObjectType()
          {abstract} + showRemovedObject()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.ShowTypesInputPort {
          {abstract} + showTypes()
      }
    }
  }
  

  namespace fourcats {
    namespace port {
      interface fourcats.port.ShowTypesOutputPort {
          {abstract} + showTypes()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
