@startuml

title __ENTITIES's Class Diagram__\n

  namespace fourcats {
    namespace Entities {
      class fourcats.entities.Action {
          - name : String
          - param : List<ObjectParam>
          - type : String
          + Action()
          + Action()
          + addObjectParam()
          + addObjectParamName()
          + getName()
          + getObjectParams()
          + getType()
          + setName()
          + setType()
          + toString()
          + updateIsObjectParamRequired()
          + updateObjectParamName()
          + updateObjectParamType()
      }
    }
  }
  

  namespace fourcats {
    namespace Entities {
      class fourcats.entities.Actor {
          - lAction : List<Action>
          - name : String
          + Actor()
          + Actor()
          + Actor()
          + addAction()
          + addActions()
          + getActions()
          + getActionsByName()
          + getName()
          + setName()
          + toString()
      }
    }
  }
  

  namespace fourcats {
    namespace Entities {
      class fourcats.entities.BAL {
          - lActors : List<Actor>
          + BAL()
          + BAL()
          + BAL()
          + addUserToBAL()
          + getActors()
          + toString()
      }
    }
  }
  

  namespace fourcats {
    namespace Entities {
      class fourcats.entities.Bdl {
          - nameBdl : String
          - nouns : LinkedList<WordCounter>
          - predicates : LinkedList<WordCounter>
          - verbs : LinkedList<WordCounter>
          + Bdl()
          + Bdl()
          + addNoun()
          + addPredicate()
          + addVerb()
          + getName()
          + getNouns()
          + getPredicates()
          + getVerbs()
          + removeNoun()
          + removePredicate()
          + removeVerb()
          + storeBdlNoun()
          + storeBdlPredicate()
          + storeBdlVerb()
          + toString()
          - order()
      }
    }
  }
  

  namespace fourcats {
    namespace Entities {
      class fourcats.entities.ObjectParam {
          - name : String
          - required : Boolean
          - type : String
          + ObjectParam()
          + ObjectParam()
          + ObjectParam()
          + getName()
          + getType()
          + isRequired()
          + setName()
          + setRequired()
          + setType()
          + toString()
      }
    }
  }
  

  namespace fourcats {
    namespace Entities {
      class fourcats.entities.Scenario {
          - actorName : String
          - content : String
          - mAction : Map<Integer, Action>
          - name : String
          + Scenario()
          + getActions()
          + getActionsMap()
          + getActorName()
          + getContent()
          + getName()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
