language: java
jdk: openjdk8
addons:
    sonarcloud:
        organization: "fourcats" # the key of the org
        token: ${SONAR_TOKEN_NATURALAPI} # encrypted value of your token
script:
    # other script steps might be done before running the actual analysis
    - cd NaturalAPI_Discover
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar
    #- mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=fourcatsteam_NaturalAPI
    #- sonar-scanner