@startuml

title __USECASEINTERACTOR's Class Diagram__\n

  namespace fourcats {
    namespace UseCaseInteractor {
      class fourcats.usecaseinteractor.DeclineBALSuggestion {
          + DeclineBALSuggestion()
          + declineSuggestion()
      }
    }
  }
  

  namespace fourcats {
    namespace UseCaseInteractor {
      class fourcats.usecaseinteractor.GenerateBAL {
          + GenerateBAL()
          + generateBAL()
      }
    }
  }
  

  namespace fourcats {
    namespace UseCaseInteractor {
      class fourcats.usecaseinteractor.GenerateBALSuggestions {
          + GenerateBALSuggestions()
          + generateSuggestions()
          - extractActorName()
          - extractScenarioName()
          - generateAction()
          - generateObject()
      }
    }
  }
  

  fourcats.usecaseinteractor.DeclineBALSuggestion .up.|> fourcats.port.DeclineBALSuggestionInputPort
  fourcats.usecaseinteractor.DeclineBALSuggestion o-- fourcats.port.DeclineBALSuggestionOutputPort : out
  fourcats.usecaseinteractor.DeclineBALSuggestion o-- fourcats.interfaceaccess.RepositoryAccess : repo
  fourcats.usecaseinteractor.GenerateBAL .up.|> fourcats.port.GenerateBALInputPort
  fourcats.usecaseinteractor.GenerateBAL o-- fourcats.interfaceaccess.BalAnalyzer : balAnalyzer
  fourcats.usecaseinteractor.GenerateBAL o-- fourcats.port.GenerateBALOutputPort : out
  fourcats.usecaseinteractor.GenerateBAL o-- fourcats.interfaceaccess.RepositoryAccess : repo
  fourcats.usecaseinteractor.GenerateBALSuggestions .up.|> fourcats.port.GenerateBALSuggestionsInputPort
  fourcats.usecaseinteractor.GenerateBALSuggestions o-- fourcats.port.GenerateBALSuggestionsOutputPort : out
  fourcats.usecaseinteractor.GenerateBALSuggestions o-- fourcats.interfaceaccess.RepositoryAccess : repo
  fourcats.usecaseinteractor.GenerateBALSuggestions o-- fourcats.interfaceaccess.TextAnalyzer : textAnalyzer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
