@startuml

title __INTERFACEACCESS's Class Diagram__\n

  namespace fourcats {
    namespace interfaceaccess {
      interface fourcats.interfaceaccess.BalAnalyzer {
          {abstract} + createJsonFromBAL()
          {abstract} + get()
          {abstract} + getBAL()
          {abstract} + getJsonNode()
          {abstract} + setBalFile()
      }
    }
  }
  

  namespace fourcats {
    namespace interfaceaccess {
      interface fourcats.interfaceaccess.PersistentMemoryAccess {
          {abstract} + loadBdl()
          {abstract} + readFile()
          {abstract} + writeFile()
      }
    }
  }
  

  namespace fourcats {
    namespace interfaceaccess {
      interface fourcats.interfaceaccess.RepositoryAccess {
          {abstract} + createBAL()
          {abstract} + createCustomType()
          {abstract} + createObject()
          {abstract} + createScenario()
          {abstract} + deleteObject()
          {abstract} + deleteScenarios()
          {abstract} + deleteSuggestion()
          {abstract} + read()
          {abstract} + readScenarios()
          {abstract} + readTypes()
          {abstract} + updateActionName()
          {abstract} + updateActionType()
          {abstract} + updateActionTypeById()
          {abstract} + updateObjectName()
          {abstract} + updateObjectType()
          {abstract} + updateObjectTypeById()
      }
    }
  }
  

  namespace fourcats {
    namespace interfaceaccess {
      interface fourcats.interfaceaccess.TextAnalyzer {
          {abstract} + parseDocumentContent()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
