package fourcats.view.gui;

import fourcats.interfaceadapters.Controller;

import javax.swing.*;
import java.awt.*;

public class AddSuggestionButtonWidget {
    private JButton addSuggestionButton;

    public AddSuggestionButtonWidget(Controller controller, String scenarioId) {
        addSuggestionButton = new JButton("+");
        addSuggestionButton.addActionListener(e -> {
            String actionName = JOptionPane.showInputDialog(null, "Insert the name for the action", "Add suggestion", JOptionPane.INFORMATION_MESSAGE).trim();
            if (!actionName.equals("")) {
                if (Character.isDigit(actionName.charAt(0))) actionName = "_" + actionName;
                controller.addSuggestion(scenarioId, actionName, "void");
            } else {
                JOptionPane.showMessageDialog(null, "Action name field can not be empty", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    JButton getButtonWidget() {
        return addSuggestionButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
