package fourcats.view.gui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.util.List;

public class AttributeWidget {
    private JPanel mainPanel;
    private JComboBox<String> attributeTypeComboBox;
    private JTextField attributeNameField;
    private JButton removeAttributeButton;
    private String attrName;
    private String attrType;

    public AttributeWidget(List<String> lAvailableTypes) {
        this.attrName = "";
        this.attrType = "string";
        attributeNameField.setMaximumSize(new Dimension(Integer.MAX_VALUE, 30));
        attributeTypeComboBox.setMaximumSize(new Dimension(Integer.MAX_VALUE / 2, 30));
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.LINE_AXIS));
        mainPanel.add(attributeTypeComboBox);
        mainPanel.add(attributeNameField);
        mainPanel.add(removeAttributeButton);

        //populate types combo box
        for (String type : lAvailableTypes) {
            attributeTypeComboBox.addItem(type);
        }

        removeAttributeButton.addActionListener(e -> {
            attributeTypeComboBox.setSelectedItem("");
            attributeNameField.setText("");
            mainPanel.setVisible(false);
        });

        attributeTypeComboBox.addActionListener(e ->
                attrType = attributeTypeComboBox.getSelectedItem().toString()
        );

        attributeNameField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setAttrName();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setAttrName();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setAttrName();
            }

            private void setAttrName() {
                attrName = attributeNameField.getText();
            }
        });

    }

    public JPanel getAttributeWidgetPanel() {
        return mainPanel;
    }

    public String getAttributeName() {
        return attrName;
    }

    public String getAttributeType() {
        return attrType;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), "Attribute", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        attributeTypeComboBox = new JComboBox();
        mainPanel.add(attributeTypeComboBox, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        attributeNameField = new JTextField();
        mainPanel.add(attributeNameField, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        removeAttributeButton = new JButton();
        removeAttributeButton.setText("-");
        mainPanel.add(removeAttributeButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}


