package fourcats.view.gui;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class ScenarioWidget extends JComponent {
    private JPanel mainPanel;
    private JTextArea featureTextArea;
    private JLabel featureLabel;
    private JLabel actorLabel;


    public ScenarioWidget(JPanel panelToUpdate, String featureName, String actor, String scenario) {
        JPanel panelNorth = new JPanel(new GridLayout(2, 1));
        panelNorth.add(featureLabel);
        panelNorth.add(actorLabel);
        actorLabel.setText("---Actor: " + actor);
        featureLabel.setText("---Feature: " + featureName);

        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.PAGE_AXIS));
        mainPanel.add(Box.createHorizontalStrut(20));
        mainPanel.add(panelNorth);
        //add text area in a scrollPane
        JScrollPane scrollPane = new JScrollPane(featureTextArea,
                ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setPreferredSize(new Dimension(370, 200));
        mainPanel.add(scrollPane);
        featureTextArea.setText(scenario);
        panelToUpdate.add(mainPanel);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), "Scenario", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        featureTextArea = new JTextArea();
        featureTextArea.setEditable(false);
        featureTextArea.setText("Given\nWhen\nThen");
        mainPanel.add(featureTextArea, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        featureLabel = new JLabel();
        featureLabel.setText("Feature: ");
        mainPanel.add(featureLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        actorLabel = new JLabel();
        actorLabel.setText("Actor:");
        mainPanel.add(actorLabel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
