@startuml

title __DATASTRUCTURE's Class Diagram__\n

  namespace fourcats {
    namespace datastructure {
      class fourcats.datastructure.AnalyzedData {
          - dependencies : LinkedList<Dependency>
          - tokens : LinkedList<WordTag>
          + AnalyzedData()
          + addDependency()
          + addLemmaData()
          + getDependenciesList()
          + getTaggedData()
          + toString()
      }
    }
  }
  

  namespace fourcats {
    namespace datastructure {
      class fourcats.datastructure.BlackList {
          - blackList : List<String>
          + BlackList()
          + BlackList()
          + addTerm()
          + addTerms()
          + contains()
      }
    }
  }
  

  namespace fourcats {
    namespace datastructure {
      class fourcats.datastructure.Dependency {
          - dep : String
          - gov : String
          - relation : String
          + Dependency()
          + getDep()
          + getGov()
          + getRelation()
      }
    }
  }
  

  namespace fourcats {
    namespace datastructure {
      class fourcats.datastructure.WordCounter {
          - count : Integer
          - word : String
          + WordCounter()
          + WordCounter()
          + compareTo()
          + decrementCounter()
          + getCount()
          + getWord()
          + incrementCounter()
          + toString()
      }
    }
  }
  

  namespace fourcats {
    namespace datastructure {
      class fourcats.datastructure.WordTag {
          - lemma : String
          - tag : String
          - value : String
          + WordTag()
          + getLemma()
          + getTag()
          + getValue()
          + toString()
      }
    }
  }
  

  fourcats.datastructure.WordCounter .up.|> java.lang.Comparable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
