@startuml

title __DATASTRUCTURE's Class Diagram__\n

  namespace fourcats {
    namespace DataStructure {
      class fourcats.datastructure.AnalyzedData {
          - parserData : LinkedList<String>
          + AnalyzedData()
          + addLemmaData()
          + addParseData()
          + getNouns()
          + getParseList()
          + getTaggedData()
          + getVerbs()
          + toString()
      }
    }
  }
  

  namespace fourcats {
    namespace DataStructure {
      class fourcats.datastructure.BlackList {
          + blackList : List<String>
          + BlackList()
          + BlackList()
          + addTerm()
          + addTerms()
          + contains()
      }
    }
  }
  

  namespace fourcats {
    namespace DataStructure {
      class fourcats.datastructure.LemmatizerData {
          - lemmatizationResult : LinkedList<WordTag>
          + LemmatizerData()
          + addElement()
          + getList()
          + getNouns()
          + getVerbs()
          + toString()
      }
    }
  }
  

  namespace fourcats {
    namespace DataStructure {
      class fourcats.datastructure.WordCounter {
          - count : Integer
          - word : String
          + WordCounter()
          + WordCounter()
          + compareTo()
          + decrementCounter()
          + getCount()
          + getWord()
          + incrementCounter()
          + toString()
      }
    }
  }
  

  namespace fourcats {
    namespace DataStructure {
      class fourcats.datastructure.WordTag {
          - lemma : String
          - tag : String
          - value : String
          + WordTag()
          + getLemma()
          + getTag()
          + getValue()
          + toString()
      }
    }
  }
  

  fourcats.datastructure.AnalyzedData o-- fourcats.datastructure.LemmatizerData : data
  fourcats.datastructure.WordCounter .up.|> java.lang.Comparable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
