@startuml

title __INTERFACEADAPTERS's Class Diagram__\n

  namespace fourcats {
    namespace interfaceadapters {
      class fourcats.interfaceadapters.Controller {
          + Controller()
          + addObject()
          + addSuggestion()
          + addSuggestionByIdType()
          + createCustomType()
          + declineSuggestion()
          + generateBAL()
          + generateSuggestions()
          + loadBdl()
          + modifyActionName()
          + modifyActionType()
          + modifyActionTypeById()
          + modifyObjectName()
          + modifyObjectType()
          + modifyObjectTypeById()
          + removeObject()
          + showTypes()
      }
    }
  }
  

  namespace fourcats {
    namespace interfaceadapters {
      class fourcats.interfaceadapters.DataPresenter {
          - toShow : String
          + getDataToShow()
          + showAddedObject()
          + showAddedSuggestion()
          + showBDLOutput()
          + showCustomTypeCreationStatus()
          + showDeclinedSuggestion()
          + showErrorFileLoad()
          + showGenerationStatus()
          + showModifiedActionName()
          + showModifiedActionType()
          + showModifiedObjectName()
          + showModifiedObjectType()
          + showRemovedObject()
          + showSuggestionsForScenario()
          + showTypes()
          - showSuggestions()
      }
    }
  }
  

  namespace fourcats {
    namespace interfaceadapters {
      class fourcats.interfaceadapters.DataPresenterGUI {
          {static} ~ ERROR_MESSAGE : String
          ~ actionName : String
          ~ actionType : String
          ~ actor : String
          ~ featurePath : String
          ~ isOkOperation : boolean
          ~ isSuggestionToAdd : boolean
          ~ isSuggestionsRefreshNeeded : boolean
          ~ lObjectId : ArrayList<String>
          ~ lObjectNames : ArrayList<String>
          ~ lObjectTypes : ArrayList<String>
          ~ lTypes : ArrayList<String>
          ~ message : String
          ~ scenarioContent : String
          ~ scenarioId : String
          ~ suggestionId : String
          - isPresentInBdl : boolean
          + DataPresenterGUI()
          + getActionName()
          + getActionType()
          + getActor()
          + getFeaturePath()
          + getMessage()
          + getScenarioContent()
          + getScenarioId()
          + getSuggestionId()
          + getlObjectId()
          + getlObjectNames()
          + getlObjectTypes()
          + getlTypes()
          + isBdlLoaded()
          + isOkOperation()
          + isPresentInBdl()
          + isSuggestionToAdd()
          + isSuggestionsRefreshNeeded()
          + showAddedObject()
          + showAddedSuggestion()
          + showBDLOutput()
          + showCustomTypeCreationStatus()
          + showDeclinedSuggestion()
          + showErrorFileLoad()
          + showGenerationStatus()
          + showModifiedActionName()
          + showModifiedActionType()
          + showModifiedObjectName()
          + showModifiedObjectType()
          + showRemovedObject()
          + showSuggestionsForScenario()
          + showTypes()
          - showSuggestions()
      }
    }
  }
  

  fourcats.interfaceadapters.Controller o-- fourcats.port.AddBALSuggestionInputPort : addSuggestion
  fourcats.interfaceadapters.Controller o-- fourcats.port.CreateCustomTypeInputPort : createCustomType
  fourcats.interfaceadapters.Controller o-- fourcats.port.DeclineBALSuggestionInputPort : declineSuggestion
  fourcats.interfaceadapters.Controller o-- fourcats.port.GenerateBALInputPort : generateBAL
  fourcats.interfaceadapters.Controller o-- fourcats.port.GenerateBALSuggestionsInputPort : generateSuggestion
  fourcats.interfaceadapters.Controller o-- fourcats.port.LoadBDLInputPort : loadBdl
  fourcats.interfaceadapters.Controller o-- fourcats.port.ModifyBALSuggestionInputPort : modifySuggestion
  fourcats.interfaceadapters.Controller o-- fourcats.port.ShowTypesInputPort : showTypes
  fourcats.interfaceadapters.DataPresenter .up.|> fourcats.port.AddBALSuggestionOutputPort
  fourcats.interfaceadapters.DataPresenter .up.|> fourcats.port.CreateCustomTypeOutputPort
  fourcats.interfaceadapters.DataPresenter .up.|> fourcats.port.DeclineBALSuggestionOutputPort
  fourcats.interfaceadapters.DataPresenter .up.|> fourcats.port.GenerateBALOutputPort
  fourcats.interfaceadapters.DataPresenter .up.|> fourcats.port.GenerateBALSuggestionsOutputPort
  fourcats.interfaceadapters.DataPresenter .up.|> fourcats.port.LoadBDLOutputPort
  fourcats.interfaceadapters.DataPresenter .up.|> fourcats.port.ModifyBALSuggestionOutputPort
  fourcats.interfaceadapters.DataPresenter .up.|> fourcats.port.ShowTypesOutputPort
  fourcats.interfaceadapters.DataPresenter -up-|> fourcats.datastructure.observer.Subject
  fourcats.interfaceadapters.DataPresenterGUI .up.|> fourcats.port.AddBALSuggestionOutputPort
  fourcats.interfaceadapters.DataPresenterGUI .up.|> fourcats.port.CreateCustomTypeOutputPort
  fourcats.interfaceadapters.DataPresenterGUI .up.|> fourcats.port.DeclineBALSuggestionOutputPort
  fourcats.interfaceadapters.DataPresenterGUI .up.|> fourcats.port.GenerateBALOutputPort
  fourcats.interfaceadapters.DataPresenterGUI .up.|> fourcats.port.GenerateBALSuggestionsOutputPort
  fourcats.interfaceadapters.DataPresenterGUI .up.|> fourcats.port.LoadBDLOutputPort
  fourcats.interfaceadapters.DataPresenterGUI .up.|> fourcats.port.ModifyBALSuggestionOutputPort
  fourcats.interfaceadapters.DataPresenterGUI .up.|> fourcats.port.ShowTypesOutputPort
  fourcats.interfaceadapters.DataPresenterGUI -up-|> fourcats.datastructure.observer.Subject
  fourcats.interfaceadapters.DataPresenterGUI o-- fourcats.SuggestionBDLAlgorithm.StrategyAlgorithm : algorithm
  fourcats.interfaceadapters.DataPresenterGUI o-- fourcats.entities.Bdl : bdlLoaded


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
