@startuml

title __FRAMEWORKS's Class Diagram__\n

  namespace fourcats {
    namespace frameworks {
      class fourcats.frameworks.BalAnalyzerImplementation {
          ~ jsonNode : JsonNode
          + BalAnalyzerImplementation()
          + BalAnalyzerImplementation()
          + BalAnalyzerImplementation()
          + createJsonFromBAL()
          + get()
          + getBAL()
          + getJsonNode()
          + setBalFile()
      }
    }
  }
  

  namespace fourcats {
    namespace frameworks {
      class fourcats.frameworks.DataKeeper {
          - lDeafultTypes : List<String>
          - mScenarios : Map<Integer, Scenario>
          - mTypes : Map<Integer, Type>
          + DataKeeper()
          + addCustomType()
          + addObject()
          + addScenarioToMap()
          + clearScenariosMap()
          + getScenarioMap()
          + getTypeMap()
          + removeAction()
          + removeObject()
          + updateActionName()
          + updateActionType()
          + updateActionTypeById()
          + updateObjectName()
          + updateObjectType()
          + updateObjectTypeById()
      }
    }
  }
  

  namespace fourcats {
    namespace frameworks {
      class fourcats.frameworks.FileSystemAccess {
          + loadBdl()
          + readFile()
          + writeFile()
          - readBdlNouns()
          - readBdlPredicates()
          - readBdlVerbs()
      }
    }
  }
  

  namespace fourcats {
    namespace frameworks {
      class fourcats.frameworks.Repository {
          + Repository()
          + createBAL()
          + createCustomType()
          + createObject()
          + createScenario()
          + deleteObject()
          + deleteScenarios()
          + deleteSuggestion()
          + read()
          + readScenarios()
          + readTypes()
          + updateActionName()
          + updateActionType()
          + updateActionTypeById()
          + updateObjectName()
          + updateObjectType()
          + updateObjectTypeById()
      }
    }
  }
  

  namespace fourcats {
    namespace frameworks {
      class fourcats.frameworks.StanfordNlp {
          {static} - DP_MODEL : String
          - depparser : DependencyParser
          - pipeline : StanfordCoreNLP
          - props : Properties
          - tokenizerFactory : TokenizerFactory<CoreLabel>
          + StanfordNlp()
          + parseDocumentContent()
      }
    }
  }
  

  fourcats.frameworks.BalAnalyzerImplementation .up.|> fourcats.interfaceaccess.BalAnalyzer
  fourcats.frameworks.FileSystemAccess .up.|> fourcats.interfaceaccess.PersistentMemoryAccess
  fourcats.frameworks.Repository .up.|> fourcats.interfaceaccess.RepositoryAccess
  fourcats.frameworks.Repository o-- fourcats.frameworks.DataKeeper : dataKeeper
  fourcats.frameworks.Repository o-- fourcats.interfaceaccess.PersistentMemoryAccess : memoryAccess
  fourcats.frameworks.StanfordNlp .up.|> fourcats.interfaceaccess.TextAnalyzer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
